name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: DockerHub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file GitHubSecretExample/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/githubsecretsexample

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubsecretsexample
