name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file GitHubSecretExample/Dockerfile -t app .
    - uses: secrethub/pushimage@v3
    - name: Publish Docker image
      run: |
          echo ${{ secrets.DOCKER_HUB_USER_NAME }} | docker login -u ${{ secrets.DOCKER_HUB_USER_PASSWORD }} --password-stdin
          docker push gencaydo/githubsecretexample
